   10REM BARSOOM
   20REM THESE ARE THE STARTING VALUES
   30NUMCREDITS=1000: NUMYEAR=0 : NUMOXYUNITS = RND(50)+1 : NUMFOODUNITS = 0
   40NUMPOP=100
   50REM BEGIN ANNUAL REPORT
   60VDU 5
   70VDU 23,17,7,6,8;14;0;
   80CLS
   90GCOL1
  100PRINT "/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#" : PRINT
  110NUMYEAR=NUMYEAR+1
  120PRINT "Barsoom Annual Report for Year: " STR$(NUMYEAR)
  130PRINT
  140REM THE GAME WILL ALSO CHECK TO SEE IF 10 YEARS HAVE PASSED.
  150REM IF THE POPULATION IS 1 OR LESS, THEN YOU'VE FAILED.
  160PRINT "Barsoom's Population is: " STR$(NUMPOP)
  170NUMFOODCOST = RND(5)+1
  180IF NUMFOODCOST = 1 THEN GOTO 170
  190PRINT
  200IF NUMYEAR >= 10 THEN PROCENDGAME
  210IF NUMPOP <= 1 THEN PROCDEATH
  220GCOL 2
  230PRINT "You have " STR$(NUMOXYUNITS) " oxygen units."
  240PRINT
  250GCOL 3
  260PRINT "You have " STR$(NUMFOODUNITS) " food units."
  270PRINT
  280GCOL 4
  290PRINT "Food costs " STR$(NUMFOODCOST) " credits per unit".
  300PRINT
  310PRINT "You have " STR$(NUMCREDITS) " credits."
  320PRINT
  330INPUT "How many food units do you wish to buy? " NUMBUYFOOD
  340PROCBUYFOOD
  350PRINT
  360GCOL 5
  370PRINT "Barsoom's population is " STR$(NUMPOP) ". You can assign up to " STR$(NUMFOODUNITS) " food units to them."
  380PRINT
  390INPUT "How many food units would you like to assign?" NUMASSIGNFOOD
  400IF NUMASSIGNFOOD > NUMFOODUNITS THEN GOTO 390 ELSE PROCASSIGNFOOD
  410PRINT
  420REM EACH CITIZEN NEEDS 1 OXYGEN UNIT PER YEAR TO SURVIVE.
  430REM THEY WILL ALWAYS MINE ENOUGH TO KEEP FROM SUFFOCATING.
  440REM ANYTHING ELSE THEY EARN IS A SURPLUS WHICH CAN BE TRADED.
  450NUMOXYMINING=NUMPOP*RND(3) : NUMOXYMINING=NUMPOP*RND(3)
  460GCOL 6
  470PRINT "This year there's been a surplus of " STR$(NUMOXYMINING) " oxygen units."
  480PRINT
  490NUMOXYPRICE = RND(4)+1 : NUMOXYPRICE = RND(4)+1
  500PRINT "Oxygen units are currently selling at " STR$(NUMOXYPRICE) " credits each."
  510GCOL 7
  520PRINT
  530INPUT "How many Oxygen units do you wish to sell?"NUMSELLOXYUNITS
  540IF NUMSELLOXYUNITS >0 THEN PROCSELLOXYGEN ELSE GOTO 50
  550DEF PROCSELLOXYGEN
  560IF NUMSELLOXYUNITS > NUMOXYMINING THEN GOTO 530
  570CLS : PRINT
  580NUMCREDITS = NUMCREDITS + (NUMSELLOXYUNITS*NUMOXYPRICE)
  590PRINT "You've sold " STR$(NUMSELLOXYUNITS) " oxygen units for " STR$(NUMOXYPRICE) " credits each. Total profit is " STR$(NUMSELLOXYUNITS*NUMOXYPRICE) " credits."
  600GOTO 50
  610ENDPROC
  620REM ABC
  630DEF PROCENDGAME
  640CLS : PRINT
  650PRINT "Well done, you finished the game!"
  660END
  670DEF PROCBUYFOOD
  680NUMTOTALFOODCOST = NUMBUYFOOD*NUMFOODCOST
  690CLS : PRINT
  700GCOL 1
  710PRINT "The cost to buy " STR$(NUMBUYFOOD) " food units is " STR$(NUMTOTALFOODCOST) " credits".
  720IF NUMTOTALFOODCOST > NUMCREDITS THEN PRINT "Sorry you don't have enough credits." : GOTO300
  730NUMCREDITS=NUMCREDITS-NUMTOTALFOODCOST
  740PRINT
  750PRINT "You successfully bought " STR$(NUMBUYFOOD) " food units for " STR$(NUMTOTALFOODCOST) " credits." : NUMFOODUNITS = NUMFOODUNITS+NUMBUYFOOD
  760ENDPROC
  770REM ASSIGN FOOD PROCEDURE
  780REM FIRSTLY IF EACH CITIZEN DOESN'T GET 1 UNIT A YEAR, THEY DIE.
  790DEF PROCASSIGNFOOD
  800CLS : PRINT
  810IF (NUMASSIGNFOOD+NUMFOODUNITS) < NUMPOP THEN NUMPOP=NUMPOP-(NUMPOP-NUMASSIGNFOOD) :  PRINT "Insufficient food. The population has fallen to " STR$(NUMPOP)
  820REM IF THERE'S A SURPLUS OF ASSIGNED FOOD THEN THE POPULATION CAN BREED
  830IF NUMASSIGNFOOD > NUMPOP THEN NUMPOP = NUMPOP + INT(NUMASSIGNFOOD/8) :  PRINT "There has been a food surplus! Population is now " STR$(NUMPOP)
  840REM OTHERWISE POPULATION REMAINS STATIC
  850ENDPROC
  860DEF PROCDEATH
  870PRINT
  880GCOL 1
  890PRINT "Barsoom's population has been wiped out. Game Over."
  900END
  910ENDPROC
